pageinfo = [[1321625531,7471],
	[1321625527,17662],
	[1321625975,8252],
	[1321625543,11308],
	[1321568433,13982],
	[1321625399,3497],
	[1321625547,8647],
	[1321626255,8130],
	[1321625549,8323],
	[1321625537,8178],
	[1321625539,9897]];
pagedata = [ ["./consolidado_partido_departamen.htm","CONSOLIDADO PARTIDO DEPARTAMENTO","﻿Top Previous Next CONSOLIDADO PARTIDO DEPARTAMENTO Permite al usuario consultar el consolidado departamental de los partidos en un departamento o...",""],
["./consolidado_partido_lista.htm","CONSOLIDADO PARTIDO LISTA","﻿Top Previous Next CONSOLIDADO PARTIDO LISTA Permite al usuario consultar y generar archivos de los datos y estadísticas de la votación obtenida, ...",""],
["./elegidos_asignacion_curules.htm","ELEGIDOS ASIGNACIÓN CURULES","﻿Top Previous ELEGIDOS ASIGNACIÓN CURULES Permite al usuario consultar los candidatos elegidos en la asignación de curules, por corporación en una...",""],
["./elegidos_corporaciones.htm","ELEGIDOS CORPORACIONES","﻿Top Previous Next ELEGIDOS CORPORACIONES Permite al usuario consultar los candidatos elegidos, por corporaciones, en un departamento o municipio....",""],
["./introduccion.htm","INTRODUCCIÓN","﻿Top Previous Next Estadísticas Electorales Escrutinio 2011 es un desarrollo web que le permitirá al usuario consultar, generar informes PDF, WORD...",""],
["./introduction.htm","MANUAL ESTADÍSTICAS","﻿Top Next Soluciones Integrales de Oficina SIO S.A. Cali ",""],
["./listado_votacion_candidatos.htm","LISTADO VOTACIÓN CANDIDATOS","﻿Top Previous Next LISTADO VOTACIÓN CANDIDATOS Permite al usuario consultar la votación obtenida por los candidatos, en un departamento o municipi...",""],
["./listas_mayor_votacion.htm","LISTAS MAYOR VOTACIÓN","﻿Top Previous Next LISTAS MAYOR VOTACIÓN Permite al usuario consultar las listas de partidos de mayor votación, por corporación y divipol. ▪ Para ...",""],
["./resumen_curules_asignadas.htm","RESUMEN CURULES ASIGNADAS","﻿Top Previous Next RESUMEN CURULES ASIGNADAS Permite al usuario consultar la cantidad de curules asignadas a un partido, por corporación y divipol...",""],
["./resumen_votacion_candidatos.htm","RESUMEN VOTACIÓN CANDIDATOS","﻿Top Previous Next RESUMEN VOTACIÓN CANDIDATOS Permite al usuario consultar la votación de los candidatos de una corporación en un municipio. ▪ Pa...",""],
["./resumen_votacion_partidos.htm","RESUMEN VOTACIÓN PARTIDOS","﻿Top Previous Next RESUMEN VOTACIÓN PARTIDOS Permite al usuario consultar la votación obtenida por los partidos en un departamento o municipio. ▪ ...",""]];
